Fix indentation to 4 space. Run autopep8 to fix most formatting.

diff --git a/init/rdiff-web b/init/rdiff-web
--- a/init/rdiff-web
+++ b/init/rdiff-web
@@ -37,59 +37,59 @@ fi
 
 # This script won't be able to run without root privileges.
 if [ `id -u` -ne 0 ]; then
-   echo "Error: this script must be run as root."
-   exit 1
+    echo "Error: this script must be run as root."
+    exit 1
 fi
 
 
 # See how we were called.
 case "$1" in
-   start)
-      if [ ! -f /etc/rdiffweb/rdw.conf ]; then
-         echo -n "rdiffWeb is not configured!  Please run 'rdiff-web-config'."
-         echo $ERROR_MSG
-         exit 1
-      fi
-      echo -n "Starting rdiffWeb..."
-      /usr/bin/rdiff-web --pid-file="$PIDFILE" \
-      --log-file="$LOGFILE" \
-      --background > /dev/null 2>&1
-      echo $SUCCESS_MSG
-      exit 0
-   ;;
+    start)
+        if [ ! -f /etc/rdiffweb/rdw.conf ]; then
+            echo -n "rdiffWeb is not configured!  Please run 'rdiff-web-config'."
+            echo $ERROR_MSG
+            exit 1
+        fi
+        echo -n "Starting rdiffWeb..."
+        /usr/bin/rdiff-web --pid-file="$PIDFILE" \
+        --log-file="$LOGFILE" \
+        --background > /dev/null 2>&1
+        echo $SUCCESS_MSG
+        exit 0
+    ;;
 
-   stop)
-      if [ -e "$PIDFILE" ]; then
-         echo -n "Stopping rdiffWeb..."
-         kill `cat "$PIDFILE" 2>/dev/null` > /dev/null 2>&1
-         rm $PIDFILE > /dev/null 2>&1
-         echo $SUCCESS_MSG
-         exit 0
-      else
-         echo -n "rdiffWeb is not running"
-         echo $ERROR_MSG
-         exit 1
-      fi
-   ;;
+    stop)
+        if [ -e "$PIDFILE" ]; then
+            echo -n "Stopping rdiffWeb..."
+            kill `cat "$PIDFILE" 2>/dev/null` > /dev/null 2>&1
+            rm $PIDFILE > /dev/null 2>&1
+            echo $SUCCESS_MSG
+            exit 0
+        else
+            echo -n "rdiffWeb is not running"
+            echo $ERROR_MSG
+            exit 1
+        fi
+    ;;
 
-   status)
-      echo -n "rdiffWeb "
-      if [ -e "$PIDFILE" ]; then
-         echo "is running."
-         exit 0
-      else
-         echo "is not running."
-         exit 1
-      fi
-   ;;
+    status)
+        echo -n "rdiffWeb "
+        if [ -e "$PIDFILE" ]; then
+            echo "is running."
+            exit 0
+        else
+            echo "is not running."
+            exit 1
+        fi
+    ;;
 
-   restart)
-      "$0" stop && "$0" start
-   ;;
+    restart)
+        "$0" stop && "$0" start
+    ;;
 
-   *)
-      echo "Usage: `basename "$0"` {start|stop|status|restart}"
-      exit 1
+    *)
+        echo "Usage: `basename "$0"` {start|stop|status|restart}"
+        exit 1
 esac
 
 exit 0
