Fix init script. Fix problem related to logs, background process.

diff --git a/init-script/rdiffweb b/init-script/rdiffweb
--- a/init-script/rdiffweb
+++ b/init-script/rdiffweb
@@ -25,45 +25,145 @@
 # Description: Manages the rdiffweb daemon
 ### END INIT INFO
 
-ACCESSLOGFILE="/var/log/rdiffweb-access.log"
-SCRIPT="/usr/local/bin/rdiffweb --background --log-access-file=$ACCESSLOGFILE"
-RUNAS=root
+## Options you may change ##
+DEBUG=0
+AUTORELOAD=0
 
-PIDFILE=/var/run/rdiffweb.pid
-LOGFILE="/var/log/rdiffweb.log"
- 
-start() {
-  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
-    echo 'Service already running' >&2
-    return 1
-  fi
-  echo 'Starting service…' >&2
-  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
-  su -c "$CMD" $RUNAS > "$PIDFILE"
-  echo 'Service started' >&2
+#DEBUG=true
+
+## Options you should probably not change ##
+DESC="rdiffweb server"
+NAME=rdiffweb
+DAEMON=/usr/local/bin/$NAME
+DAEMON_ARGS=""
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+
+LOGFILE="/var/log/$NAME.log"
+ACCESSLOGFILE="/var/log/$NAME-access.log"
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+#. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+## Build extra options ##
+DAEMON_ARGS="--log-access-file=$ACCESSLOGFILE --log-file=$LOGFILE"
+if [ "$DEBUG" = "1" ]; then
+  DAEMON_ARGS="$DAEMON_ARGS --debug"
+fi
+if [ "$AUTORELOAD" = "1" ]; then
+  DAEMON_ARGS="$DAEMON_ARGS --autoreload"
+fi
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+  # Return
+  #   0 if daemon has been started
+  #   1 if daemon was already running
+  #   2 if daemon could not be started
+  start-stop-daemon --start --background --quiet \
+    --pidfile $PIDFILE --startas $DAEMON --test > /dev/null \
+    || return 1
+  start-stop-daemon --start --background --quiet \
+    --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- \
+    $DAEMON_ARGS \
+    || return 2
 }
- 
-stop() {
-  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
-    echo 'Service not running' >&2
-    return 1
-  fi
-  echo 'Stopping service…' >&2
-  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
-  echo 'Service stopped' >&2
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+  # Return
+  #   0 if daemon has been stopped
+  #   1 if daemon was already stopped
+  #   2 if daemon could not be stopped
+  #   other if a failure occurred
+  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+  RETVAL="$?"
+  [ "$RETVAL" = 2 ] && return 2
+  # Wait for children to finish too if this is a daemon that forks
+  # and if the daemon is only ever run from this initscript.
+  # If the above conditions are not satisfied then add some other code
+  # that waits for the process to drop all resources that could be
+  # needed by services started subsequently.  A last resort is to
+  # sleep for some time.
+  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+  [ "$?" = 2 ] && return 2
+  # Many daemons don't delete their pidfiles when they exit.
+  rm -f $PIDFILE
+  return "$RETVAL"
 }
- 
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+  #
+  # If the daemon can reload its configuration without
+  # restarting (for example, when it is sent a SIGHUP),
+  # then implement that here.
+  #
+  start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+  return 0
+}
+
 case "$1" in
   start)
-    start
-    ;;
+  [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+  do_start
+  case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+  esac
+  ;;
   stop)
-    stop
+  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+  esac
+  ;;
+  status)
+  status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+  ;;
+  restart|force-reload)
+  log_daemon_msg "Restarting $DESC" "$NAME"
+  do_stop
+  case "$?" in
+    0|1)
+    do_start
+    case "$?" in
+      0) log_end_msg 0 ;;
+      1) log_end_msg 1 ;; # Old process is still running
+      *) log_end_msg 1 ;; # Failed to start
+    esac
     ;;
-  restart)
-    stop
-    start
+    *)
+    # Failed to stop
+    log_end_msg 1
     ;;
+  esac
+  ;;
   *)
-    echo "Usage: $0 {start|stop|restart}"
+  echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+  exit 3
+  ;;
 esac
+
+:
